### ISSUE TITLE
Error when querying a ton of rows with 'All Rows' query type

### ISSUE THREAD

**Issue by levent2014** [tagyoureit/InfluxDB_WDC#11]
When using Tableau to visit Influxdb with  'All Rows' ,  Json parsed error occurs  if the measurement contains a ton of rows (my measurement has over 10 million rows).   I debugged this and found  the response string was empty  after request was sent by wdc to influxdb . See the screenshot below.  Is there any solution for this problem?
![image](https://user-images.githubusercontent.com/13374023/50267140-26c08200-0461-11e9-920d-0b119b1d8bc1.png)

**Comment by tagyoureit** [comment]
Have you tried with a smaller table?  Please let me know if it has something to do with the size.

If you can also attach the full console output I might be able to debug further.

**Comment by levent2014** [comment]
Perhaps it has nothing  to do with your code.  I've tried with data of smaller size (about 500 thousand)  from the same table, and it works well. I guess it has something to do with Influxdb which is unable to output large amount of data through HTTP in time. In Tableau Community Forums I found a discussion about performance of wdc.  (https://community.tableau.com/thread/206611) .  It seems like wdc cannot support  large datasets well.  Below is console  output, and some sensitive information has been covered.
![image](https://user-images.githubusercontent.com/13374023/50326334-c430ba00-0524-11e9-9f72-20f290b95b8a.png)

![image](https://user-images.githubusercontent.com/13374023/50335848-8b560c80-0547-11e9-8066-1a281246af33.png)

**Comment by tagyoureit** [comment]
A few of thoughts...

1.  Can you look on the server to see if there are any errors in the log when returning the query?  If the WDC can return 500k rows maybe something is timing out on the server side?
1. Do you happen to have a machine available with more available memory?  Since the returned format is JSON it is going to be pretty 'heavy' and maybe the browser that is processing the resultset is running out of memory?
1.  You could do a simple test to run the http query direct in the browser to make sure that it returns all results.  
1.  You could try a custom sql and specify a chunk size.  I already add "&chunked=true" but maybe changing the [chunk size](https://docs.influxdata.com/influxdb/v1.7/guides/querying_data/#chunking) will have a beneficial effect?  EG "Select * from {table} limit 1000000 chuck_size=200000".  I haven't tested this out so try some different bucket sizes and see if there is any impact.
1.  If you turn on [desktop debugging](http://tableau.github.io/webdataconnector/docs/wdc_debugging.html#debugging-tableau) in Tableau Desktop maybe some useful errors will surface (The WDC Simulator is notoriously buggy and not sure if the screenshot you provided was from Desktop debugging or the simulator.)
1.  Can you aggregate the results to 5 minutes or some other level where you return fewer results?  
1.  Soon (with Prep Conductor) you could create a "base" extract, import it into Tableau and then add maybe daily/weekly results and union them together.  But this probably isn't a viable solution yet.

I thought about trying to fix this on the code side (eg allow for multiple calls to the same table to union them together) but I just don't think it is possible with the current implementation.

**Comment by Jocoleqy** [comment]
> A few of thoughts...
> 
> 1. Can you look on the server to see if there are any errors in the log when returning the query?  If the WDC can return 500k rows maybe something is timing out on the server side?
> 2. Do you happen to have a machine available with more available memory?  Since the returned format is JSON it is going to be pretty 'heavy' and maybe the browser that is processing the resultset is running out of memory?
> 3. You could do a simple test to run the http query direct in the browser to make sure that it returns all results.
> 4. You could try a custom sql and specify a chunk size.  I already add "&chunked=true" but maybe changing the [chunk size](https://docs.influxdata.com/influxdb/v1.7/guides/querying_data/#chunking) will have a beneficial effect?  EG "Select * from {table} limit 1000000 chuck_size=200000".  I haven't tested this out so try some different bucket sizes and see if there is any impact.
> 5. If you turn on [desktop debugging](http://tableau.github.io/webdataconnector/docs/wdc_debugging.html#debugging-tableau) in Tableau Desktop maybe some useful errors will surface (The WDC Simulator is notoriously buggy and not sure if the screenshot you provided was from Desktop debugging or the simulator.)
> 6. Can you aggregate the results to 5 minutes or some other level where you return fewer results?
> 7. Soon (with Prep Conductor) you could create a "base" extract, import it into Tableau and then add maybe daily/weekly results and union them together.  But this probably isn't a viable solution yet.
> 
> I thought about trying to fix this on the code side (eg allow for multiple calls to the same table to union them together) but I just don't think it is possible with the current implementation.

Thanks for your detailed reply. I've tried your suggestions and I think it has got to be a time-out problem. Perhaps wdc focuses on generality instead of performance. My table is increasing at speed of 3 million rows per day, now it's quite large , so I choose your 7th suggestion, the Extract to meet my need .

**Comment by levent2014** [comment]
> A few of thoughts...
> 
> 1. Can you look on the server to see if there are any errors in the log when returning the query?  If the WDC can return 500k rows maybe something is timing out on the server side?
> 2. Do you happen to have a machine available with more available memory?  Since the returned format is JSON it is going to be pretty 'heavy' and maybe the browser that is processing the resultset is running out of memory?
> 3. You could do a simple test to run the http query direct in the browser to make sure that it returns all results.
> 4. You could try a custom sql and specify a chunk size.  I already add "&chunked=true" but maybe changing the [chunk size](https://docs.influxdata.com/influxdb/v1.7/guides/querying_data/#chunking) will have a beneficial effect?  EG "Select * from {table} limit 1000000 chuck_size=200000".  I haven't tested this out so try some different bucket sizes and see if there is any impact.
> 5. If you turn on [desktop debugging](http://tableau.github.io/webdataconnector/docs/wdc_debugging.html#debugging-tableau) in Tableau Desktop maybe some useful errors will surface (The WDC Simulator is notoriously buggy and not sure if the screenshot you provided was from Desktop debugging or the simulator.)
> 6. Can you aggregate the results to 5 minutes or some other level where you return fewer results?
> 7. Soon (with Prep Conductor) you could create a "base" extract, import it into Tableau and then add maybe daily/weekly results and union them together.  But this probably isn't a viable solution yet.
> 
> I thought about trying to fix this on the code side (eg allow for multiple calls to the same table to union them together) but I just don't think it is possible with the current implementation.

Thanks for your detailed reply. I've tried your suggestions and I think it has got to be a time-out problem. Perhaps wdc focuses on generality instead of performance. My table is increasing at speed of 3 million rows per day, now it's quite large , so I choose your 7th suggestion, the Extract to meet my need .

**Comment by tagyoureit** [comment]
Ok, glad to hear there is a viable solution.  Closing this out.
