### ISSUE TITLE
Influx DB - Tableau Web Data Connector Error

### ISSUE THREAD

**Issue by Faouzizi** [tagyoureit/InfluxDB_WDC#19]
Hi,
 
I use this WDC since a long time ago and since 5 february 2021, this connector no longer works. 
I still can ping the influxdb using http. 
The error that a i have on Tableau 2019.2 is : 
"SyntaxError: Invalid character: '`' file: https://tagyoureit.github.io/InfluxDB_WDC/InfluxDB_WDC.js line: 68" 
and on Tableau 2020.4 is 
"Error loading database: {"readyState":0,"status":0,"statusText":"error"}"

I think that you should replace **`** by **'** in the InfluxDB_WDC.js file.

@tagyoureit  Do you have more information about this issue ? 
Regards

**Comment by brucee64** [comment]
I also ran into the same error as @Faouzizi
This was working before the last update.

**Comment by tagyoureit** [comment]
The invalid character should be fixed now.  I upgrade to ES6 code not remembering it didn't work on 2019.3 or older versions.

The error you were seeing on 2020.4 could very likely be a CORS limitation.  With Tableau 2019.4+ you cannot query http content because the WDC is being served from https site.  You can either install the wdc locally and serve it over http or [enable https on Influx](https://docs.influxdata.com/influxdb/v1.8/administration/https_setup/).

Please let me know if this fixes the issue.

**Comment by Faouzizi** [comment]
It's work well on Tableau 2019.2.  

Thank you @tagyoureit
